POST http://localhost:30699/users
Content-Type: application/json

  {
    "email": "kirkrohani@gmail.com",
    "password": "@Password01",
    "firstName": "kirk",
    "lastName": "rohani"
}

POST http://localhost:30699/auth/login
Content-Type: application/json

{
    "email": "kirkrohani@gmail.com",
    "password": "@Password01"
}