POST http://localhost:30699/users
Content-Type: application/json

  {
    "email": "kirk.rohani@gmail.com",
    "password": "@Password02",
    "firstName": "kirk2",
    "lastName": "rohani2"
}

POST http://34.111.148.190/auth/login
Content-Type: application/json

{
    "email": "kirk.rohani@gmail.com",
    "password": "@Password02"
}