steps:
  #Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/reserveme-458502/reservations/production_1.0.0',
      '-f',
      'apps/reservations/Dockerfile',
      '.',
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'push',
      'us-east4-docker.pkg.dev/reserveme-458502/reservations/production_1.0.0',
     ]

  #Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/reserveme-458502/auth/production_1.0.0',
      '-f',
      'apps/auth/Dockerfile',
      '.',
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'push',
      'us-east4-docker.pkg.dev/reserveme-458502/auth/production_1.0.0',
     ]

  #Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/reserveme-458502/payments/production_1.0.0',
      '-f',
      'apps/payments/Dockerfile',
      '.',
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'push',
      'us-east4-docker.pkg.dev/reserveme-458502/payments/production_1.0.0',
     ]

  #Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/reserveme-458502/notifications/production_1.0.0',
      '-f',
      'apps/notifications/Dockerfile',
      '.',
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args:   [
      'push',
      'us-east4-docker.pkg.dev/reserveme-458502/notifications/production_1.0.0',
     ]
#Adding some general comments