POST http://localhost:3000/reservations
Content-Type: application/json

{
  "startDate": "04-30-2025",
  "endDate": "05-01-2025",
  "invoiceId": "1236",
  "charge": {
    "amount": 11,
    "card": {
      "cvc": "413",
      "exp_month": 12,
      "exp_year": 2027,
      "number": "4242 4242 4242 4242"
    }
  }
}