POST http://localhost:31665/reservations
Content-Type: application/json

{
  "startDate": "05-08-2025",
  "endDate": "05-09-2025",
  "invoiceId": "1236",
  "charge": {
    "amount": 270,
    "card": {
      "cvc": "413",
      "exp_month": 12,
      "exp_year": 2027,
      "number": "4242 4242 4242 4242"
    }
  }
}