services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image:  183695703212.dkr.ecr.us-east-1.amazonaws.com/reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: 183695703212.dkr.ecr.us-east-1.amazonaws.com/auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: 183695703212.dkr.ecr.us-east-1.amazonaws.com/payments:latest
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: 183695703212.dkr.ecr.us-east-1.amazonaws.com/notifications
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo